version: '2.1'








# +------------------------+    +------------------------+    +------------------------+    +------------------------+    +------------------------+
# |                        |    |                        |    |                        |    |                        |    |                        |
# |    app0_dnsserver      |    |    app1_mailserver     |    |    app2_customserver   |    |  app3_customhttpserver |    |  app4_??????           |
# | The DNS server         |    | The mail server        |    |  Requests the IP       |    | The DNS server         |    |                        |
# | receive name requests  |    | receive IMAP/POP/SMTP  |    |  address of the        |    | receive name requests  |    |                        |
# | (nslookup google.com)  |    | requests to send or    |    |  mail server (app1)    |    | (nslookup google.com)  |    |                        |
# | and returns the        |    | receive mail           |    |  to the dns server     |    | and returns the        |    |                        |
# | related IP             |    |                        |    |  (app0)                |    | related IP             |    |                        |
# |                        |    | hostname mail.intranet |    |                        |    |                        |    |                        |
# |  IP      101.1.0.10    |    |  IP      101.1.0.11    |    |  IP      101.1.0.12    |    |  IP      101.1.0.13    |    |  IP      101.1.0.14    |
# |  Netmast 255.255.255.0 |    |  Netmast 255.255.255.0 |    |  Netmast 255.255.255.0 |    |  Netmast 255.255.255.0 |    |  Netmast 255.255.255.0 |
# |  Gateway 101.1.0.254   |    |  Gateway 101.1.0.254   |    |  Gateway 101.1.0.254   |    |  Gateway 101.1.0.254   |    |  Gateway 101.1.0.254   |
# |  DNS Server 101.1.0.10 |    |  DNS server 101.1.0.10 |    |  DNS server 101.1.0.10 |    |  DNS server 101.1.0.10 |    |  DNS server 101.1.0.10 |
# +------------------------+    +------------------------+    +------------------------+    +------------------------+    +------------------------+
#             |                              |                             |                             |                             |
#             +------------------------------+--------------+--------------+-----------------------------+-----------------------------+
#                                                           |
#                                              +------------------------+
#                                              |                        |
#                                              |    gateway0            |
#                                              | Connects the intranet  |
#                                              | to the internet or     |
#                                              | another intranet       |
#                                              |                        |
#                                              |                        |
#                                              |                        |
#                                              |  IP      101.1.0.254   |
#                                              |  Netmast 255.255.255.0 |
#                                              +------------------------+
#                                                          |
#                                                          |  
#                     +------------------------+           |                                                 
#                     |                        |           |                                                 
#                     | Docker Virtual adapter |           |                                                 
#  +----------+       |                        |           |                                                 
#  |          |       |  Connects to the       |           |                                                 
#  | Host PC  |       |  internet using a real |-----------+                                                 
#  |    &     |-------|  network adapter       |           |                                                 
#  | Internet |       |  through the OS itself |           |                                                 
#  |          |       |                        |           |                                                 
#  +----------+       |  IP      192.168.99.1  |           |                                                 
#                     |  Netmast 255.255.255.0 |           |                                                 
#                     +------------------------+           |                                                 
#                                                          |  
#                                              +------------------------+
#                                              |                        |
#                                              |    gateway1            |
#                                              | Connects the intranet  |
#                                              | to the internet or     |
#                                              | another intranet       |
#                                              |                        |
#                                              |                        |
#                                              |                        |
#                                              |  IP      101.2.0.254   |
#                                              |  Netmast 255.255.255.0 |
#                                              +------------------------+
#                                                           |
#                                                           |
#                                                           |
#             +------------------------------+--------------+--------------+-----------------------------+
#             |                              |                             |                             |
# +------------------------+    +------------------------+    +------------------------+    +------------------------+
# |                        |    |                        |    |                        |    |                        |
# |    app5_dnsserver      |    |    app6_????           |    |    app7_?????          |    |  app8_??????           |
# |  The DNS server        |    |                        |    |                        |    |                        |
# |  receive name requests |    |                        |    |                        |    |                        |
# |  (nslookup google.com) |    |                        |    |                        |    |                        |
# |  and returns the       |    |                        |    |                        |    |                        |
# |  related IP            |    |                        |    |                        |    |                        |
# |                        |    | hostname mail.intranet |    |                        |    |                        |
# |  IP      101.2.0.10    |    |  IP      101.2.0.11    |    |  IP      101.2.0.12    |    |  IP      101.2.0.13    |
# |  Netmast 255.255.255.0 |    |  Netmast 255.255.255.0 |    |  Netmast 255.255.255.0 |    |  Netmast 255.255.255.0 |
# |  Gateway 101.2.0.254   |    |  Gateway 101.2.0.254   |    |  Gateway 101.2.0.254   |    |  Gateway 101.2.0.254   |
# |  DNS Server 101.2.0.10 |    |  DNS server 101.2.0.10 |    |  DNS server 101.2.0.10 |    |  DNS server 101.2.0.10 |
# +------------------------+    +------------------------+    +------------------------+    +------------------------+

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local

services:
    gateway0:
      container_name: gateway0
      mem_limit: 128M
      build: 
        context: ./
        #Look at https://github.com/manell/wireshark for more info
        dockerfile: Dockerfile_gateway_with_wireshark 
      volumes:
        #If you're using Docker Toolbox (with VirtualBox) on Windows, your source folder should be on your User path
        #If you're using Linux, chmod a+rwx /my_path to allow external write and sudo chown my_user /my_path/output.pcap

        - /c/Users/Gabriel/pasta_trabalho:/data 
      command: bash -c "tshark -ni 1 -w /data/output.pcap"
      privileged: true
      networks:
          net1:
            ipv4_address: 101.1.0.254
      dns: 101.1.0.10

    app0_dnsserver:
      #Look at https://github.com/phensley/docker-dns for more info
      image: phensley/docker-dns
      domainname: intranet
      container_name: dns
      command: --domain intranet
      mem_limit: 128M
      networks:
          net1:
            ipv4_address: 101.1.0.10
      volumes:
          - /var/run/docker.sock:/docker.sock 


    app1_mailserver:
        #Look at https://hub.docker.com/r/tvial/docker-mailserver/ for more info
        image: tvial/docker-mailserver:latest
        hostname: mail
        domainname: intranet
        mem_limit: 512M
        container_name: mail
        ports:
          - "25:25"
          - "143:143"
          - "587:587"
          - "993:993"
        volumes:
          - maildata:/var/mail
          - mailstate:/var/mail-state
          - ./config/:/tmp/docker-mailserver/
        environment:
          - ENABLE_SPAMASSASSIN=1
          - ENABLE_CLAMAV=1
          - ENABLE_FAIL2BAN=1
          - ENABLE_POSTGREY=1
          - ONE_DIR=1
          - DMS_DEBUG=0
        cap_add:
          - NET_ADMIN
          - SYS_PTRACE
        networks:
            net1:
                ipv4_address: 101.1.0.11
        dns: 101.1.0.10
        
    app2_customserver:
        hostname: pinger
        domainname: intranet
        container_name: pinger
        mem_limit: 128M
        build: 
            context: ./
            dockerfile: Dockerfile_customserver 
        command: bash -c "sleep 20; ping -c 200 mail.intranet" #start required services
        networks:
            net1:
                ipv4_address: 101.1.0.12 
        dns: 101.1.0.10

    
# TODO:
#    app3_sshserver:
#        mem_limit: 128M 
#        build: ./Dockerfile_app3
#        networks:
#            net1:
#                ipv4_address: 101.1.0.13 
#
#    app4_customhttpserver:
#        mem_limit: 128M
#        build: ./Dockerfile_app4
#        networks:
#            net1:
#                ipv4_address: 101.1.0.14 
#    
#    app5_sendandreceivemail:
#        mem_limit: 128M
#        build: ./Dockerfile_app4
#        networks:
#            net2:
#                ipv4_address: 101.2.0.10 
#
#    app6_dnslookupclient:
#        mem_limit: 128M
#        build: ./Dockerfile_app4
#        networks:
#            net2:
#                ipv4_address: 101.2.0.11 
#
#    app7_sshclient:
#        mem_limit: 128M
#        build: ./Dockerfile_app4
#        networks:
#            net2:
#                ipv4_address: 101.2.0.12 
#    
#    app8_customhttpclient:
#        hostname: host8
#        mem_limit: 128M
#        build: ./Dockerfile_app4
#        networks:
#            net2:
#                ipv4_address: 101.2.0.13 
        

networks:
    #The bridge driver used below creates a switch for each subnetwork, 
    # and this switch also serves as a border router, linking the subnetwork to the host network

    net1:
        # use the bridge driver, but enable IPv6
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 101.1.0.0/24
                  default-gateway: 101.1.0.254
                  dns: 101.1.0.10


    net2:
        # use the bridge driver, but enable IPv6
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 101.2.0.0/24
                  default-gateway: 101.2.0.254
                  dns: 101.2.0.10

